TRUNCATE TABLE tourist
INSERT INTO tourist (birth_date, credit_card, destination, gender, id_type, name, travel_budget, travel_frecuency, id) VALUES ('birth1', 1 , 'destination1' , 'M' , 'type1' , 'name1' , 1.0 , 1 , '1')
INSERT INTO tourist (birth_date, credit_card, destination, gender, id_type, name, travel_budget, travel_frecuency, id) VALUES ('birth2', 0 , 'destination2' , 'M' , 'type2' , 'name2' , 1.1 , 12 , '2')
INSERT INTO tourist (birth_date, credit_card, destination, gender, id_type, name, travel_budget, travel_frecuency, id) VALUES ('birth3', 1 , 'destination3' , 'M' , 'type3' , 'name3' , 1.2 , 13 , '3')
INSERT INTO tourist (birth_date, credit_card, destination, gender, id_type, name, travel_budget, travel_frecuency, id) VALUES ('birth4', 1 , 'destination4' , 'F' , 'type4' , 'name4' , 1.3 , 14 , '4')
INSERT INTO tourist (birth_date, credit_card, destination, gender, id_type, name, travel_budget, travel_frecuency, id) VALUES ('birth5', 1 , 'destination5' , 'F' , 'type5' , 'name5' , 1.4 , 15 , '5')
INSERT INTO tourist (birth_date, credit_card, destination, gender, id_type, name, travel_budget, travel_frecuency, id) VALUES ('birth6', 0 , 'destination6' , 'F' , 'type6' , 'name6' , 1.5 , 16 , '6')
INSERT INTO tourist (birth_date, credit_card, destination, gender, id_type, name, travel_budget, travel_frecuency, id) VALUES ('birth7', 0 , 'destination7' , 'F' , 'type7' , 'name7' , 1.6 , 17 , '7')
INSERT INTO tourist (birth_date, credit_card, destination, gender, id_type, name, travel_budget, travel_frecuency, id) VALUES ('birth8', 0 , 'destination8' , 'F' , 'type8' , 'name8' , 1.7 , 18 , '8')
INSERT INTO tourist (birth_date, credit_card, destination, gender, id_type, name, travel_budget, travel_frecuency, id) VALUES ('birth9', 1 , 'destination9' , 'F' , 'type9' , 'name9' , 1.8 , 19 , '9')
